version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    command: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    ports:
      - "${KEYCLOAK_PORT}:8080"
    restart: always
    command: -v start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/:ro
